-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "referral_code" character varying NULL, "credit_balance" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"), CONSTRAINT "users_credit_balance_non_negative" CHECK ("credit_balance" >= 0));
-- create index "user_name_email" to table: "users"
CREATE INDEX "user_name_email" ON "users" ("name", "email");
-- create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- create index "users_referral_code_key" to table: "users"
CREATE UNIQUE INDEX "users_referral_code_key" ON "users" ("referral_code");
-- set comment to table: "users"
COMMENT ON TABLE "users" IS 'User table stores all user information.';
-- create "referrals" table
CREATE TABLE "referrals" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "reward" bigint NOT NULL, "inviter_id" bigint NOT NULL, "invitee_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "referrals_users_sent_referrals" FOREIGN KEY ("inviter_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "referrals_users_received_referral" FOREIGN KEY ("invitee_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "referrals_reward_positive" CHECK ("reward" > 0));
CREATE INDEX "referral_inviter_id" ON "referrals" ("inviter_id");
CREATE UNIQUE INDEX "referrals_invitee_id_key" ON "referrals" ("invitee_id");
-- create "credit_transactions" table
CREATE TABLE "credit_transactions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "amount" bigint NOT NULL, "reason" character varying NOT NULL, "referral_id" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "credit_transactions_referrals_credit_transaction" FOREIGN KEY ("referral_id") REFERENCES "referrals" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "credit_transactions_users_credit_transactions" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
CREATE UNIQUE INDEX "credit_transactions_referral_id_key" ON "credit_transactions" ("referral_id");
CREATE INDEX "credittransaction_user_id" ON "credit_transactions" ("user_id");
