ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "referral_code" character varying NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "credit_balance" bigint NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_credit_balance_non_negative') THEN
    ALTER TABLE "users" ADD CONSTRAINT "users_credit_balance_non_negative" CHECK ("credit_balance" >= 0);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS "user_name_email" ON "users" ("name", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "users_referral_code_key" ON "users" ("referral_code");

CREATE TABLE IF NOT EXISTS "referrals" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "reward" bigint NOT NULL,
  "inviter_id" bigint NOT NULL,
  "invitee_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "referrals_users_sent_referrals" FOREIGN KEY ("inviter_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "referrals_users_received_referral" FOREIGN KEY ("invitee_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "referrals_reward_positive" CHECK ("reward" > 0)
);
CREATE INDEX IF NOT EXISTS "referral_inviter_id" ON "referrals" ("inviter_id");
CREATE UNIQUE INDEX IF NOT EXISTS "referrals_invitee_id_key" ON "referrals" ("invitee_id");

CREATE TABLE IF NOT EXISTS "credit_transactions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "amount" bigint NOT NULL,
  "reason" character varying NOT NULL,
  "referral_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "credit_transactions_referrals_credit_transaction" FOREIGN KEY ("referral_id") REFERENCES "referrals" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "credit_transactions_users_credit_transactions" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS "credit_transactions_referral_id_key" ON "credit_transactions" ("referral_id");
CREATE INDEX IF NOT EXISTS "credittransaction_user_id" ON "credit_transactions" ("user_id");
