CREATE TABLE "permission_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "module" character varying NOT NULL,
  "description" character varying NOT NULL DEFAULT '',
  "parent_id" bigint NULL,
  "sort_order" bigint NOT NULL DEFAULT 0,
  "enabled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id"),
  CONSTRAINT "permission_groups_permission_groups_children" FOREIGN KEY ("parent_id") REFERENCES "permission_groups" ("id") ON DELETE SET NULL
);
CREATE INDEX "permissiongroup_parent_id" ON "permission_groups" ("parent_id");
CREATE INDEX "permissiongroup_module" ON "permission_groups" ("module");

ALTER TABLE "permissions" ADD COLUMN "group_id" bigint NULL;
ALTER TABLE "permissions" ADD CONSTRAINT "permissions_permission_groups_permissions" FOREIGN KEY ("group_id") REFERENCES "permission_groups" ("id") ON DELETE SET NULL;
ALTER TABLE "menus" ADD COLUMN "component" character varying NOT NULL DEFAULT '';
ALTER TABLE "menus" ADD COLUMN "redirect" character varying NOT NULL DEFAULT '';

CREATE TABLE "api_resources" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "method" character varying NOT NULL,
  "path" character varying NOT NULL,
  "description" character varying NOT NULL DEFAULT '',
  "enabled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "apiresource_method_path" ON "api_resources" ("method", "path");
CREATE INDEX "apiresource_enabled" ON "api_resources" ("enabled");

CREATE TABLE "permission_apis" (
  "permission_id" bigint NOT NULL,
  "api_resource_id" bigint NOT NULL,
  PRIMARY KEY ("permission_id", "api_resource_id"),
  CONSTRAINT "permission_apis_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE,
  CONSTRAINT "permission_apis_api_resource_id" FOREIGN KEY ("api_resource_id") REFERENCES "api_resources" ("id") ON DELETE CASCADE
);
CREATE TABLE "permission_menus" (
  "permission_id" bigint NOT NULL,
  "menu_id" bigint NOT NULL,
  PRIMARY KEY ("permission_id", "menu_id"),
  CONSTRAINT "permission_menus_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE,
  CONSTRAINT "permission_menus_menu_id" FOREIGN KEY ("menu_id") REFERENCES "menus" ("id") ON DELETE CASCADE
);

CREATE TABLE "permission_audit_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "operator_id" bigint NOT NULL,
  "action" character varying NOT NULL,
  "target_type" character varying NOT NULL,
  "target_id" bigint NOT NULL,
  "request_id" character varying NOT NULL DEFAULT '',
  "ip_address" character varying NOT NULL DEFAULT '',
  "details" jsonb NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "permissionauditlog_operator_id_create_time" ON "permission_audit_logs" ("operator_id", "create_time");
CREATE INDEX "permissionauditlog_target_type_target_id" ON "permission_audit_logs" ("target_type", "target_id");

INSERT INTO "permission_groups" ("create_time", "update_time", "name", "module", "description", "sort_order") VALUES
  (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '系统权限', 'system', '系统与权限管理', 10),
  (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '推荐管理', 'referral', '推荐关系与积分管理', 20);
UPDATE "permissions" p SET "group_id" = g.id FROM "permission_groups" g WHERE p.module = g.module;
