ALTER TABLE "users" ADD COLUMN "enabled" boolean NOT NULL DEFAULT true;

CREATE TABLE "menus" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "path" character varying NOT NULL DEFAULT '',
  "icon" character varying NOT NULL DEFAULT '',
  "type" character varying NOT NULL DEFAULT 'MENU',
  "parent_id" bigint NULL,
  "sort_order" bigint NOT NULL DEFAULT 0,
  "enabled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id"),
  CONSTRAINT "menus_menus_children" FOREIGN KEY ("parent_id") REFERENCES "menus" ("id") ON DELETE SET NULL,
  CONSTRAINT "menus_type_check" CHECK ("type" IN ('CATALOG', 'MENU', 'BUTTON', 'EMBEDDED', 'LINK'))
);
CREATE INDEX "menu_parent_id" ON "menus" ("parent_id");
CREATE INDEX "menu_sort_order" ON "menus" ("sort_order");

CREATE TABLE "permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "code" character varying NOT NULL,
  "module" character varying NOT NULL DEFAULT 'system',
  "description" character varying NOT NULL DEFAULT '',
  "enabled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "permissions_code_key" ON "permissions" ("code");
CREATE INDEX "permission_module" ON "permissions" ("module");
CREATE INDEX "permission_enabled" ON "permissions" ("enabled");

CREATE TABLE "roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "code" character varying NOT NULL,
  "description" character varying NOT NULL DEFAULT '',
  "enabled" boolean NOT NULL DEFAULT true,
  "is_system" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "roles_code_key" ON "roles" ("code");
CREATE INDEX "role_enabled" ON "roles" ("enabled");

CREATE TABLE "role_permissions" (
  "role_id" bigint NOT NULL,
  "permission_id" bigint NOT NULL,
  PRIMARY KEY ("role_id", "permission_id"),
  CONSTRAINT "role_permissions_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE,
  CONSTRAINT "role_permissions_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE
);
CREATE TABLE "role_menus" (
  "role_id" bigint NOT NULL,
  "menu_id" bigint NOT NULL,
  PRIMARY KEY ("role_id", "menu_id"),
  CONSTRAINT "role_menus_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE,
  CONSTRAINT "role_menus_menu_id" FOREIGN KEY ("menu_id") REFERENCES "menus" ("id") ON DELETE CASCADE
);
CREATE TABLE "user_roles" (
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("user_id", "role_id"),
  CONSTRAINT "user_roles_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "user_roles_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE
);

INSERT INTO "permissions" ("create_time", "update_time", "name", "code", "module", "description")
VALUES
  (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '权限系统管理', 'system:rbac', 'system', '管理角色、权限点、菜单和用户授权'),
  (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '邀请奖励查看', 'referral:read', 'referral', '查看全局邀请记录、奖励流水与统计');
INSERT INTO "roles" ("create_time", "update_time", "name", "code", "description", "is_system")
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '超级管理员', 'super_admin', '系统内置的完整管理权限', true);
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id FROM "roles" r CROSS JOIN "permissions" p WHERE r.code = 'super_admin' AND p.code IN ('system:rbac', 'referral:read');
INSERT INTO "user_roles" ("user_id", "role_id")
SELECT u.id, r.id FROM "users" u CROSS JOIN "roles" r WHERE r.code = 'super_admin' AND u.id = (SELECT MIN(id) FROM "users")
ON CONFLICT DO NOTHING;
