// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldReferralCode holds the string denoting the referral_code field in the database.
	FieldReferralCode = "referral_code"
	// FieldCreditBalance holds the string denoting the credit_balance field in the database.
	FieldCreditBalance = "credit_balance"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// EdgeSentReferrals holds the string denoting the sent_referrals edge name in mutations.
	EdgeSentReferrals = "sent_referrals"
	// EdgeReceivedReferral holds the string denoting the received_referral edge name in mutations.
	EdgeReceivedReferral = "received_referral"
	// EdgeCreditTransactions holds the string denoting the credit_transactions edge name in mutations.
	EdgeCreditTransactions = "credit_transactions"
	// EdgeRoles holds the string denoting the roles edge name in mutations.
	EdgeRoles = "roles"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SentReferralsTable is the table that holds the sent_referrals relation/edge.
	SentReferralsTable = "referrals"
	// SentReferralsInverseTable is the table name for the Referral entity.
	// It exists in this package in order to avoid circular dependency with the "referral" package.
	SentReferralsInverseTable = "referrals"
	// SentReferralsColumn is the table column denoting the sent_referrals relation/edge.
	SentReferralsColumn = "inviter_id"
	// ReceivedReferralTable is the table that holds the received_referral relation/edge.
	ReceivedReferralTable = "referrals"
	// ReceivedReferralInverseTable is the table name for the Referral entity.
	// It exists in this package in order to avoid circular dependency with the "referral" package.
	ReceivedReferralInverseTable = "referrals"
	// ReceivedReferralColumn is the table column denoting the received_referral relation/edge.
	ReceivedReferralColumn = "invitee_id"
	// CreditTransactionsTable is the table that holds the credit_transactions relation/edge.
	CreditTransactionsTable = "credit_transactions"
	// CreditTransactionsInverseTable is the table name for the CreditTransaction entity.
	// It exists in this package in order to avoid circular dependency with the "credittransaction" package.
	CreditTransactionsInverseTable = "credit_transactions"
	// CreditTransactionsColumn is the table column denoting the credit_transactions relation/edge.
	CreditTransactionsColumn = "user_id"
	// RolesTable is the table that holds the roles relation/edge. The primary key declared below.
	RolesTable = "user_roles"
	// RolesInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RolesInverseTable = "roles"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldName,
	FieldEmail,
	FieldReferralCode,
	FieldCreditBalance,
	FieldEnabled,
	FieldPasswordHash,
}

var (
	// RolesPrimaryKey and RolesColumn2 are the table columns denoting the
	// primary key for the roles relation (M2M).
	RolesPrimaryKey = []string{"user_id", "role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultCreditBalance holds the default value on creation for the "credit_balance" field.
	DefaultCreditBalance int
	// CreditBalanceValidator is a validator for the "credit_balance" field. It is called by the builders before save.
	CreditBalanceValidator func(int) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByReferralCode orders the results by the referral_code field.
func ByReferralCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferralCode, opts...).ToFunc()
}

// ByCreditBalance orders the results by the credit_balance field.
func ByCreditBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditBalance, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// BySentReferralsCount orders the results by sent_referrals count.
func BySentReferralsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSentReferralsStep(), opts...)
	}
}

// BySentReferrals orders the results by sent_referrals terms.
func BySentReferrals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSentReferralsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReceivedReferralField orders the results by received_referral field.
func ByReceivedReferralField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReceivedReferralStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreditTransactionsCount orders the results by credit_transactions count.
func ByCreditTransactionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreditTransactionsStep(), opts...)
	}
}

// ByCreditTransactions orders the results by credit_transactions terms.
func ByCreditTransactions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreditTransactionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRolesCount orders the results by roles count.
func ByRolesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRolesStep(), opts...)
	}
}

// ByRoles orders the results by roles terms.
func ByRoles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRolesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSentReferralsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SentReferralsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SentReferralsTable, SentReferralsColumn),
	)
}
func newReceivedReferralStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReceivedReferralInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ReceivedReferralTable, ReceivedReferralColumn),
	)
}
func newCreditTransactionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreditTransactionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreditTransactionsTable, CreditTransactionsColumn),
	)
}
func newRolesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, RolesTable, RolesPrimaryKey...),
	)
}
