// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keep/sunny/ent/apiresource"
	"github.com/keep/sunny/ent/permission"
	"github.com/keep/sunny/ent/predicate"
)

// APIResourceUpdate is the builder for updating APIResource entities.
type APIResourceUpdate struct {
	config
	hooks    []Hook
	mutation *APIResourceMutation
}

// Where appends a list predicates to the APIResourceUpdate builder.
func (_u *APIResourceUpdate) Where(ps ...predicate.APIResource) *APIResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *APIResourceUpdate) SetUpdateTime(v time.Time) *APIResourceUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *APIResourceUpdate) SetName(v string) *APIResourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIResourceUpdate) SetNillableName(v *string) *APIResourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *APIResourceUpdate) SetMethod(v string) *APIResourceUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *APIResourceUpdate) SetNillableMethod(v *string) *APIResourceUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *APIResourceUpdate) SetPath(v string) *APIResourceUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *APIResourceUpdate) SetNillablePath(v *string) *APIResourceUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APIResourceUpdate) SetDescription(v string) *APIResourceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APIResourceUpdate) SetNillableDescription(v *string) *APIResourceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *APIResourceUpdate) SetEnabled(v bool) *APIResourceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *APIResourceUpdate) SetNillableEnabled(v *bool) *APIResourceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_u *APIResourceUpdate) AddPermissionIDs(ids ...int) *APIResourceUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_u *APIResourceUpdate) AddPermissions(v ...*Permission) *APIResourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// Mutation returns the APIResourceMutation object of the builder.
func (_u *APIResourceUpdate) Mutation() *APIResourceMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (_u *APIResourceUpdate) ClearPermissions() *APIResourceUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (_u *APIResourceUpdate) RemovePermissionIDs(ids ...int) *APIResourceUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (_u *APIResourceUpdate) RemovePermissions(v ...*Permission) *APIResourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIResourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIResourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := apiresource.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIResourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apiresource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIResource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := apiresource.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "APIResource.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := apiresource.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "APIResource.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := apiresource.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "APIResource.description": %w`, err)}
		}
	}
	return nil
}

func (_u *APIResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apiresource.Table, apiresource.Columns, sqlgraph.NewFieldSpec(apiresource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(apiresource.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apiresource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(apiresource.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(apiresource.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apiresource.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(apiresource.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apiresource.PermissionsTable,
			Columns: apiresource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apiresource.PermissionsTable,
			Columns: apiresource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apiresource.PermissionsTable,
			Columns: apiresource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiresource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIResourceUpdateOne is the builder for updating a single APIResource entity.
type APIResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIResourceMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *APIResourceUpdateOne) SetUpdateTime(v time.Time) *APIResourceUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *APIResourceUpdateOne) SetName(v string) *APIResourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIResourceUpdateOne) SetNillableName(v *string) *APIResourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *APIResourceUpdateOne) SetMethod(v string) *APIResourceUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *APIResourceUpdateOne) SetNillableMethod(v *string) *APIResourceUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *APIResourceUpdateOne) SetPath(v string) *APIResourceUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *APIResourceUpdateOne) SetNillablePath(v *string) *APIResourceUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APIResourceUpdateOne) SetDescription(v string) *APIResourceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APIResourceUpdateOne) SetNillableDescription(v *string) *APIResourceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *APIResourceUpdateOne) SetEnabled(v bool) *APIResourceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *APIResourceUpdateOne) SetNillableEnabled(v *bool) *APIResourceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_u *APIResourceUpdateOne) AddPermissionIDs(ids ...int) *APIResourceUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_u *APIResourceUpdateOne) AddPermissions(v ...*Permission) *APIResourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// Mutation returns the APIResourceMutation object of the builder.
func (_u *APIResourceUpdateOne) Mutation() *APIResourceMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (_u *APIResourceUpdateOne) ClearPermissions() *APIResourceUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (_u *APIResourceUpdateOne) RemovePermissionIDs(ids ...int) *APIResourceUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (_u *APIResourceUpdateOne) RemovePermissions(v ...*Permission) *APIResourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// Where appends a list predicates to the APIResourceUpdate builder.
func (_u *APIResourceUpdateOne) Where(ps ...predicate.APIResource) *APIResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIResourceUpdateOne) Select(field string, fields ...string) *APIResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIResource entity.
func (_u *APIResourceUpdateOne) Save(ctx context.Context) (*APIResource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIResourceUpdateOne) SaveX(ctx context.Context) *APIResource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIResourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := apiresource.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIResourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apiresource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIResource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := apiresource.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "APIResource.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := apiresource.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "APIResource.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := apiresource.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "APIResource.description": %w`, err)}
		}
	}
	return nil
}

func (_u *APIResourceUpdateOne) sqlSave(ctx context.Context) (_node *APIResource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apiresource.Table, apiresource.Columns, sqlgraph.NewFieldSpec(apiresource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIResource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apiresource.FieldID)
		for _, f := range fields {
			if !apiresource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apiresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(apiresource.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apiresource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(apiresource.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(apiresource.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apiresource.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(apiresource.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apiresource.PermissionsTable,
			Columns: apiresource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apiresource.PermissionsTable,
			Columns: apiresource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apiresource.PermissionsTable,
			Columns: apiresource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIResource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiresource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
