// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/keep/sunny/ent/credittransaction"
	"github.com/keep/sunny/ent/referral"
	"github.com/keep/sunny/ent/user"
)

// CreditTransaction is the model entity for the CreditTransaction schema.
type CreditTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ReferralID holds the value of the "referral_id" field.
	ReferralID int `json:"referral_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int `json:"amount,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CreditTransactionQuery when eager-loading is set.
	Edges        CreditTransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CreditTransactionEdges holds the relations/edges for other nodes in the graph.
type CreditTransactionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Referral holds the value of the referral edge.
	Referral *Referral `json:"referral,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CreditTransactionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ReferralOrErr returns the Referral value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CreditTransactionEdges) ReferralOrErr() (*Referral, error) {
	if e.Referral != nil {
		return e.Referral, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: referral.Label}
	}
	return nil, &NotLoadedError{edge: "referral"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credittransaction.FieldID, credittransaction.FieldUserID, credittransaction.FieldReferralID, credittransaction.FieldAmount:
			values[i] = new(sql.NullInt64)
		case credittransaction.FieldReason:
			values[i] = new(sql.NullString)
		case credittransaction.FieldCreateTime, credittransaction.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditTransaction fields.
func (_m *CreditTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credittransaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case credittransaction.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case credittransaction.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case credittransaction.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case credittransaction.FieldReferralID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referral_id", values[i])
			} else if value.Valid {
				_m.ReferralID = int(value.Int64)
			}
		case credittransaction.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = int(value.Int64)
			}
		case credittransaction.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *CreditTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CreditTransaction entity.
func (_m *CreditTransaction) QueryUser() *UserQuery {
	return NewCreditTransactionClient(_m.config).QueryUser(_m)
}

// QueryReferral queries the "referral" edge of the CreditTransaction entity.
func (_m *CreditTransaction) QueryReferral() *ReferralQuery {
	return NewCreditTransactionClient(_m.config).QueryReferral(_m)
}

// Update returns a builder for updating this CreditTransaction.
// Note that you need to call CreditTransaction.Unwrap() before calling this method if this CreditTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreditTransaction) Update() *CreditTransactionUpdateOne {
	return NewCreditTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreditTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreditTransaction) Unwrap() *CreditTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreditTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("CreditTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("referral_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferralID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteByte(')')
	return builder.String()
}

// CreditTransactions is a parsable slice of CreditTransaction.
type CreditTransactions []*CreditTransaction
