// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keep/sunny/ent/credittransaction"
	"github.com/keep/sunny/ent/referral"
	"github.com/keep/sunny/ent/user"
)

// CreditTransactionCreate is the builder for creating a CreditTransaction entity.
type CreditTransactionCreate struct {
	config
	mutation *CreditTransactionMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *CreditTransactionCreate) SetCreateTime(v time.Time) *CreditTransactionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *CreditTransactionCreate) SetNillableCreateTime(v *time.Time) *CreditTransactionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *CreditTransactionCreate) SetUpdateTime(v time.Time) *CreditTransactionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *CreditTransactionCreate) SetNillableUpdateTime(v *time.Time) *CreditTransactionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CreditTransactionCreate) SetUserID(v int) *CreditTransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetReferralID sets the "referral_id" field.
func (_c *CreditTransactionCreate) SetReferralID(v int) *CreditTransactionCreate {
	_c.mutation.SetReferralID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CreditTransactionCreate) SetAmount(v int) *CreditTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *CreditTransactionCreate) SetReason(v string) *CreditTransactionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CreditTransactionCreate) SetUser(v *User) *CreditTransactionCreate {
	return _c.SetUserID(v.ID)
}

// SetReferral sets the "referral" edge to the Referral entity.
func (_c *CreditTransactionCreate) SetReferral(v *Referral) *CreditTransactionCreate {
	return _c.SetReferralID(v.ID)
}

// Mutation returns the CreditTransactionMutation object of the builder.
func (_c *CreditTransactionCreate) Mutation() *CreditTransactionMutation {
	return _c.mutation
}

// Save creates the CreditTransaction in the database.
func (_c *CreditTransactionCreate) Save(ctx context.Context) (*CreditTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreditTransactionCreate) SaveX(ctx context.Context) *CreditTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreditTransactionCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := credittransaction.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := credittransaction.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreditTransactionCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "CreditTransaction.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "CreditTransaction.update_time"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CreditTransaction.user_id"`)}
	}
	if _, ok := _c.mutation.ReferralID(); !ok {
		return &ValidationError{Name: "referral_id", err: errors.New(`ent: missing required field "CreditTransaction.referral_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CreditTransaction.amount"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "CreditTransaction.reason"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CreditTransaction.user"`)}
	}
	if len(_c.mutation.ReferralIDs()) == 0 {
		return &ValidationError{Name: "referral", err: errors.New(`ent: missing required edge "CreditTransaction.referral"`)}
	}
	return nil
}

func (_c *CreditTransactionCreate) sqlSave(ctx context.Context) (*CreditTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreditTransactionCreate) createSpec() (*CreditTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credittransaction.Table, sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(credittransaction.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(credittransaction.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(credittransaction.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(credittransaction.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credittransaction.UserTable,
			Columns: []string{credittransaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReferralIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   credittransaction.ReferralTable,
			Columns: []string{credittransaction.ReferralColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReferralID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CreditTransactionCreateBulk is the builder for creating many CreditTransaction entities in bulk.
type CreditTransactionCreateBulk struct {
	config
	err      error
	builders []*CreditTransactionCreate
}

// Save creates the CreditTransaction entities in the database.
func (_c *CreditTransactionCreateBulk) Save(ctx context.Context) ([]*CreditTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreditTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreditTransactionCreateBulk) SaveX(ctx context.Context) []*CreditTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
