// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keep/sunny/ent/permissionauditlog"
	"github.com/keep/sunny/ent/predicate"
)

// PermissionAuditLogUpdate is the builder for updating PermissionAuditLog entities.
type PermissionAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *PermissionAuditLogMutation
}

// Where appends a list predicates to the PermissionAuditLogUpdate builder.
func (_u *PermissionAuditLogUpdate) Where(ps ...predicate.PermissionAuditLog) *PermissionAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *PermissionAuditLogUpdate) SetOperatorID(v int) *PermissionAuditLogUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *PermissionAuditLogUpdate) SetNillableOperatorID(v *int) *PermissionAuditLogUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *PermissionAuditLogUpdate) AddOperatorID(v int) *PermissionAuditLogUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *PermissionAuditLogUpdate) SetAction(v string) *PermissionAuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *PermissionAuditLogUpdate) SetNillableAction(v *string) *PermissionAuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *PermissionAuditLogUpdate) SetTargetType(v string) *PermissionAuditLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *PermissionAuditLogUpdate) SetNillableTargetType(v *string) *PermissionAuditLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *PermissionAuditLogUpdate) SetTargetID(v int) *PermissionAuditLogUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *PermissionAuditLogUpdate) SetNillableTargetID(v *int) *PermissionAuditLogUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *PermissionAuditLogUpdate) AddTargetID(v int) *PermissionAuditLogUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *PermissionAuditLogUpdate) SetRequestID(v string) *PermissionAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *PermissionAuditLogUpdate) SetNillableRequestID(v *string) *PermissionAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *PermissionAuditLogUpdate) SetIPAddress(v string) *PermissionAuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *PermissionAuditLogUpdate) SetNillableIPAddress(v *string) *PermissionAuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *PermissionAuditLogUpdate) SetDetails(v map[string]interface{}) *PermissionAuditLogUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *PermissionAuditLogUpdate) ClearDetails() *PermissionAuditLogUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// Mutation returns the PermissionAuditLogMutation object of the builder.
func (_u *PermissionAuditLogUpdate) Mutation() *PermissionAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermissionAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermissionAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionAuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := permissionauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := permissionauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := permissionauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := permissionauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *PermissionAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permissionauditlog.Table, permissionauditlog.Columns, sqlgraph.NewFieldSpec(permissionauditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(permissionauditlog.FieldOperatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(permissionauditlog.FieldOperatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(permissionauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(permissionauditlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(permissionauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(permissionauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(permissionauditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(permissionauditlog.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(permissionauditlog.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(permissionauditlog.FieldDetails, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissionauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermissionAuditLogUpdateOne is the builder for updating a single PermissionAuditLog entity.
type PermissionAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermissionAuditLogMutation
}

// SetOperatorID sets the "operator_id" field.
func (_u *PermissionAuditLogUpdateOne) SetOperatorID(v int) *PermissionAuditLogUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *PermissionAuditLogUpdateOne) SetNillableOperatorID(v *int) *PermissionAuditLogUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *PermissionAuditLogUpdateOne) AddOperatorID(v int) *PermissionAuditLogUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *PermissionAuditLogUpdateOne) SetAction(v string) *PermissionAuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *PermissionAuditLogUpdateOne) SetNillableAction(v *string) *PermissionAuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *PermissionAuditLogUpdateOne) SetTargetType(v string) *PermissionAuditLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *PermissionAuditLogUpdateOne) SetNillableTargetType(v *string) *PermissionAuditLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *PermissionAuditLogUpdateOne) SetTargetID(v int) *PermissionAuditLogUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *PermissionAuditLogUpdateOne) SetNillableTargetID(v *int) *PermissionAuditLogUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *PermissionAuditLogUpdateOne) AddTargetID(v int) *PermissionAuditLogUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *PermissionAuditLogUpdateOne) SetRequestID(v string) *PermissionAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *PermissionAuditLogUpdateOne) SetNillableRequestID(v *string) *PermissionAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *PermissionAuditLogUpdateOne) SetIPAddress(v string) *PermissionAuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *PermissionAuditLogUpdateOne) SetNillableIPAddress(v *string) *PermissionAuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *PermissionAuditLogUpdateOne) SetDetails(v map[string]interface{}) *PermissionAuditLogUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *PermissionAuditLogUpdateOne) ClearDetails() *PermissionAuditLogUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// Mutation returns the PermissionAuditLogMutation object of the builder.
func (_u *PermissionAuditLogUpdateOne) Mutation() *PermissionAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the PermissionAuditLogUpdate builder.
func (_u *PermissionAuditLogUpdateOne) Where(ps ...predicate.PermissionAuditLog) *PermissionAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermissionAuditLogUpdateOne) Select(field string, fields ...string) *PermissionAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PermissionAuditLog entity.
func (_u *PermissionAuditLogUpdateOne) Save(ctx context.Context) (*PermissionAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionAuditLogUpdateOne) SaveX(ctx context.Context) *PermissionAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermissionAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := permissionauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := permissionauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := permissionauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := permissionauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "PermissionAuditLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *PermissionAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *PermissionAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permissionauditlog.Table, permissionauditlog.Columns, sqlgraph.NewFieldSpec(permissionauditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PermissionAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permissionauditlog.FieldID)
		for _, f := range fields {
			if !permissionauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permissionauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(permissionauditlog.FieldOperatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(permissionauditlog.FieldOperatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(permissionauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(permissionauditlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(permissionauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(permissionauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(permissionauditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(permissionauditlog.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(permissionauditlog.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(permissionauditlog.FieldDetails, field.TypeJSON)
	}
	_node = &PermissionAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissionauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
