// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/keep/sunny/ent/permissionauditlog"
)

// PermissionAuditLog is the model entity for the PermissionAuditLog schema.
type PermissionAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// OperatorID holds the value of the "operator_id" field.
	OperatorID int `json:"operator_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID int `json:"target_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// Details holds the value of the "details" field.
	Details      map[string]interface{} `json:"details,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PermissionAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case permissionauditlog.FieldDetails:
			values[i] = new([]byte)
		case permissionauditlog.FieldID, permissionauditlog.FieldOperatorID, permissionauditlog.FieldTargetID:
			values[i] = new(sql.NullInt64)
		case permissionauditlog.FieldAction, permissionauditlog.FieldTargetType, permissionauditlog.FieldRequestID, permissionauditlog.FieldIPAddress:
			values[i] = new(sql.NullString)
		case permissionauditlog.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PermissionAuditLog fields.
func (_m *PermissionAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case permissionauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case permissionauditlog.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case permissionauditlog.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = int(value.Int64)
			}
		case permissionauditlog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case permissionauditlog.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case permissionauditlog.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = int(value.Int64)
			}
		case permissionauditlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case permissionauditlog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case permissionauditlog.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PermissionAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *PermissionAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PermissionAuditLog.
// Note that you need to call PermissionAuditLog.Unwrap() before calling this method if this PermissionAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PermissionAuditLog) Update() *PermissionAuditLogUpdateOne {
	return NewPermissionAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PermissionAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PermissionAuditLog) Unwrap() *PermissionAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PermissionAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PermissionAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("PermissionAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("operator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", _m.Details))
	builder.WriteByte(')')
	return builder.String()
}

// PermissionAuditLogs is a parsable slice of PermissionAuditLog.
type PermissionAuditLogs []*PermissionAuditLog
