// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/keep/sunny/ent/permissiongroup"
)

// PermissionGroup is the model entity for the PermissionGroup schema.
type PermissionGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Module holds the value of the "module" field.
	Module string `json:"module,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *int `json:"parent_id,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PermissionGroupQuery when eager-loading is set.
	Edges        PermissionGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PermissionGroupEdges holds the relations/edges for other nodes in the graph.
type PermissionGroupEdges struct {
	// Parent holds the value of the parent edge.
	Parent *PermissionGroup `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*PermissionGroup `json:"children,omitempty"`
	// Permissions holds the value of the permissions edge.
	Permissions []*Permission `json:"permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PermissionGroupEdges) ParentOrErr() (*PermissionGroup, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: permissiongroup.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e PermissionGroupEdges) ChildrenOrErr() ([]*PermissionGroup, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e PermissionGroupEdges) PermissionsOrErr() ([]*Permission, error) {
	if e.loadedTypes[2] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PermissionGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case permissiongroup.FieldEnabled:
			values[i] = new(sql.NullBool)
		case permissiongroup.FieldID, permissiongroup.FieldParentID, permissiongroup.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case permissiongroup.FieldName, permissiongroup.FieldModule, permissiongroup.FieldDescription:
			values[i] = new(sql.NullString)
		case permissiongroup.FieldCreateTime, permissiongroup.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PermissionGroup fields.
func (_m *PermissionGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case permissiongroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case permissiongroup.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case permissiongroup.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case permissiongroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case permissiongroup.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				_m.Module = value.String
			}
		case permissiongroup.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case permissiongroup.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(int)
				*_m.ParentID = int(value.Int64)
			}
		case permissiongroup.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case permissiongroup.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PermissionGroup.
// This includes values selected through modifiers, order, etc.
func (_m *PermissionGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the PermissionGroup entity.
func (_m *PermissionGroup) QueryParent() *PermissionGroupQuery {
	return NewPermissionGroupClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the PermissionGroup entity.
func (_m *PermissionGroup) QueryChildren() *PermissionGroupQuery {
	return NewPermissionGroupClient(_m.config).QueryChildren(_m)
}

// QueryPermissions queries the "permissions" edge of the PermissionGroup entity.
func (_m *PermissionGroup) QueryPermissions() *PermissionQuery {
	return NewPermissionGroupClient(_m.config).QueryPermissions(_m)
}

// Update returns a builder for updating this PermissionGroup.
// Note that you need to call PermissionGroup.Unwrap() before calling this method if this PermissionGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PermissionGroup) Update() *PermissionGroupUpdateOne {
	return NewPermissionGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PermissionGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PermissionGroup) Unwrap() *PermissionGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PermissionGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PermissionGroup) String() string {
	var builder strings.Builder
	builder.WriteString("PermissionGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("module=")
	builder.WriteString(_m.Module)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// PermissionGroups is a parsable slice of PermissionGroup.
type PermissionGroups []*PermissionGroup
