// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keep/sunny/ent/permission"
	"github.com/keep/sunny/ent/permissiongroup"
)

// PermissionGroupCreate is the builder for creating a PermissionGroup entity.
type PermissionGroupCreate struct {
	config
	mutation *PermissionGroupMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *PermissionGroupCreate) SetCreateTime(v time.Time) *PermissionGroupCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableCreateTime(v *time.Time) *PermissionGroupCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *PermissionGroupCreate) SetUpdateTime(v time.Time) *PermissionGroupCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableUpdateTime(v *time.Time) *PermissionGroupCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PermissionGroupCreate) SetName(v string) *PermissionGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetModule sets the "module" field.
func (_c *PermissionGroupCreate) SetModule(v string) *PermissionGroupCreate {
	_c.mutation.SetModule(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PermissionGroupCreate) SetDescription(v string) *PermissionGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableDescription(v *string) *PermissionGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *PermissionGroupCreate) SetParentID(v int) *PermissionGroupCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableParentID(v *int) *PermissionGroupCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *PermissionGroupCreate) SetSortOrder(v int) *PermissionGroupCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableSortOrder(v *int) *PermissionGroupCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PermissionGroupCreate) SetEnabled(v bool) *PermissionGroupCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableEnabled(v *bool) *PermissionGroupCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetParent sets the "parent" edge to the PermissionGroup entity.
func (_c *PermissionGroupCreate) SetParent(v *PermissionGroup) *PermissionGroupCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the PermissionGroup entity by IDs.
func (_c *PermissionGroupCreate) AddChildIDs(ids ...int) *PermissionGroupCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the PermissionGroup entity.
func (_c *PermissionGroupCreate) AddChildren(v ...*PermissionGroup) *PermissionGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_c *PermissionGroupCreate) AddPermissionIDs(ids ...int) *PermissionGroupCreate {
	_c.mutation.AddPermissionIDs(ids...)
	return _c
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_c *PermissionGroupCreate) AddPermissions(v ...*Permission) *PermissionGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionIDs(ids...)
}

// Mutation returns the PermissionGroupMutation object of the builder.
func (_c *PermissionGroupCreate) Mutation() *PermissionGroupMutation {
	return _c.mutation
}

// Save creates the PermissionGroup in the database.
func (_c *PermissionGroupCreate) Save(ctx context.Context) (*PermissionGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionGroupCreate) SaveX(ctx context.Context) *PermissionGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PermissionGroupCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := permissiongroup.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := permissiongroup.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := permissiongroup.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := permissiongroup.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := permissiongroup.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionGroupCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "PermissionGroup.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "PermissionGroup.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PermissionGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := permissiongroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "PermissionGroup.module"`)}
	}
	if v, ok := _c.mutation.Module(); ok {
		if err := permissiongroup.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "PermissionGroup.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := permissiongroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "PermissionGroup.sort_order"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PermissionGroup.enabled"`)}
	}
	return nil
}

func (_c *PermissionGroupCreate) sqlSave(ctx context.Context) (*PermissionGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionGroupCreate) createSpec() (*PermissionGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissiongroup.Table, sqlgraph.NewFieldSpec(permissiongroup.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(permissiongroup.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(permissiongroup.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(permissiongroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Module(); ok {
		_spec.SetField(permissiongroup.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(permissiongroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(permissiongroup.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(permissiongroup.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissiongroup.ParentTable,
			Columns: []string{permissiongroup.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissiongroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.ChildrenTable,
			Columns: []string{permissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissiongroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermissionGroupCreateBulk is the builder for creating many PermissionGroup entities in bulk.
type PermissionGroupCreateBulk struct {
	config
	err      error
	builders []*PermissionGroupCreate
}

// Save creates the PermissionGroup entities in the database.
func (_c *PermissionGroupCreateBulk) Save(ctx context.Context) ([]*PermissionGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionGroupCreateBulk) SaveX(ctx context.Context) []*PermissionGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
