// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/keep/sunny/ent/apiresource"
	"github.com/keep/sunny/ent/credittransaction"
	"github.com/keep/sunny/ent/menu"
	"github.com/keep/sunny/ent/permission"
	"github.com/keep/sunny/ent/permissionauditlog"
	"github.com/keep/sunny/ent/permissiongroup"
	"github.com/keep/sunny/ent/referral"
	"github.com/keep/sunny/ent/role"
	"github.com/keep/sunny/ent/schema"
	"github.com/keep/sunny/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiresourceMixin := schema.APIResource{}.Mixin()
	apiresourceMixinFields0 := apiresourceMixin[0].Fields()
	_ = apiresourceMixinFields0
	apiresourceFields := schema.APIResource{}.Fields()
	_ = apiresourceFields
	// apiresourceDescCreateTime is the schema descriptor for create_time field.
	apiresourceDescCreateTime := apiresourceMixinFields0[0].Descriptor()
	// apiresource.DefaultCreateTime holds the default value on creation for the create_time field.
	apiresource.DefaultCreateTime = apiresourceDescCreateTime.Default.(func() time.Time)
	// apiresourceDescUpdateTime is the schema descriptor for update_time field.
	apiresourceDescUpdateTime := apiresourceMixinFields0[1].Descriptor()
	// apiresource.DefaultUpdateTime holds the default value on creation for the update_time field.
	apiresource.DefaultUpdateTime = apiresourceDescUpdateTime.Default.(func() time.Time)
	// apiresource.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	apiresource.UpdateDefaultUpdateTime = apiresourceDescUpdateTime.UpdateDefault.(func() time.Time)
	// apiresourceDescName is the schema descriptor for name field.
	apiresourceDescName := apiresourceFields[0].Descriptor()
	// apiresource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apiresource.NameValidator = func() func(string) error {
		validators := apiresourceDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apiresourceDescMethod is the schema descriptor for method field.
	apiresourceDescMethod := apiresourceFields[1].Descriptor()
	// apiresource.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	apiresource.MethodValidator = func() func(string) error {
		validators := apiresourceDescMethod.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(method string) error {
			for _, fn := range fns {
				if err := fn(method); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apiresourceDescPath is the schema descriptor for path field.
	apiresourceDescPath := apiresourceFields[2].Descriptor()
	// apiresource.PathValidator is a validator for the "path" field. It is called by the builders before save.
	apiresource.PathValidator = func() func(string) error {
		validators := apiresourceDescPath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_path string) error {
			for _, fn := range fns {
				if err := fn(_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apiresourceDescDescription is the schema descriptor for description field.
	apiresourceDescDescription := apiresourceFields[3].Descriptor()
	// apiresource.DefaultDescription holds the default value on creation for the description field.
	apiresource.DefaultDescription = apiresourceDescDescription.Default.(string)
	// apiresource.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	apiresource.DescriptionValidator = apiresourceDescDescription.Validators[0].(func(string) error)
	// apiresourceDescEnabled is the schema descriptor for enabled field.
	apiresourceDescEnabled := apiresourceFields[4].Descriptor()
	// apiresource.DefaultEnabled holds the default value on creation for the enabled field.
	apiresource.DefaultEnabled = apiresourceDescEnabled.Default.(bool)
	credittransactionMixin := schema.CreditTransaction{}.Mixin()
	credittransactionMixinFields0 := credittransactionMixin[0].Fields()
	_ = credittransactionMixinFields0
	credittransactionFields := schema.CreditTransaction{}.Fields()
	_ = credittransactionFields
	// credittransactionDescCreateTime is the schema descriptor for create_time field.
	credittransactionDescCreateTime := credittransactionMixinFields0[0].Descriptor()
	// credittransaction.DefaultCreateTime holds the default value on creation for the create_time field.
	credittransaction.DefaultCreateTime = credittransactionDescCreateTime.Default.(func() time.Time)
	// credittransactionDescUpdateTime is the schema descriptor for update_time field.
	credittransactionDescUpdateTime := credittransactionMixinFields0[1].Descriptor()
	// credittransaction.DefaultUpdateTime holds the default value on creation for the update_time field.
	credittransaction.DefaultUpdateTime = credittransactionDescUpdateTime.Default.(func() time.Time)
	// credittransaction.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	credittransaction.UpdateDefaultUpdateTime = credittransactionDescUpdateTime.UpdateDefault.(func() time.Time)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreateTime is the schema descriptor for create_time field.
	menuDescCreateTime := menuMixinFields0[0].Descriptor()
	// menu.DefaultCreateTime holds the default value on creation for the create_time field.
	menu.DefaultCreateTime = menuDescCreateTime.Default.(func() time.Time)
	// menuDescUpdateTime is the schema descriptor for update_time field.
	menuDescUpdateTime := menuMixinFields0[1].Descriptor()
	// menu.DefaultUpdateTime holds the default value on creation for the update_time field.
	menu.DefaultUpdateTime = menuDescUpdateTime.Default.(func() time.Time)
	// menu.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	menu.UpdateDefaultUpdateTime = menuDescUpdateTime.UpdateDefault.(func() time.Time)
	// menuDescName is the schema descriptor for name field.
	menuDescName := menuFields[0].Descriptor()
	// menu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menu.NameValidator = func() func(string) error {
		validators := menuDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[1].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menu.PathValidator is a validator for the "path" field. It is called by the builders before save.
	menu.PathValidator = menuDescPath.Validators[0].(func(string) error)
	// menuDescIcon is the schema descriptor for icon field.
	menuDescIcon := menuFields[2].Descriptor()
	// menu.DefaultIcon holds the default value on creation for the icon field.
	menu.DefaultIcon = menuDescIcon.Default.(string)
	// menu.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	menu.IconValidator = menuDescIcon.Validators[0].(func(string) error)
	// menuDescComponent is the schema descriptor for component field.
	menuDescComponent := menuFields[3].Descriptor()
	// menu.DefaultComponent holds the default value on creation for the component field.
	menu.DefaultComponent = menuDescComponent.Default.(string)
	// menu.ComponentValidator is a validator for the "component" field. It is called by the builders before save.
	menu.ComponentValidator = menuDescComponent.Validators[0].(func(string) error)
	// menuDescRedirect is the schema descriptor for redirect field.
	menuDescRedirect := menuFields[4].Descriptor()
	// menu.DefaultRedirect holds the default value on creation for the redirect field.
	menu.DefaultRedirect = menuDescRedirect.Default.(string)
	// menu.RedirectValidator is a validator for the "redirect" field. It is called by the builders before save.
	menu.RedirectValidator = menuDescRedirect.Validators[0].(func(string) error)
	// menuDescSortOrder is the schema descriptor for sort_order field.
	menuDescSortOrder := menuFields[7].Descriptor()
	// menu.DefaultSortOrder holds the default value on creation for the sort_order field.
	menu.DefaultSortOrder = menuDescSortOrder.Default.(int)
	// menuDescEnabled is the schema descriptor for enabled field.
	menuDescEnabled := menuFields[8].Descriptor()
	// menu.DefaultEnabled holds the default value on creation for the enabled field.
	menu.DefaultEnabled = menuDescEnabled.Default.(bool)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreateTime is the schema descriptor for create_time field.
	permissionDescCreateTime := permissionMixinFields0[0].Descriptor()
	// permission.DefaultCreateTime holds the default value on creation for the create_time field.
	permission.DefaultCreateTime = permissionDescCreateTime.Default.(func() time.Time)
	// permissionDescUpdateTime is the schema descriptor for update_time field.
	permissionDescUpdateTime := permissionMixinFields0[1].Descriptor()
	// permission.DefaultUpdateTime holds the default value on creation for the update_time field.
	permission.DefaultUpdateTime = permissionDescUpdateTime.Default.(func() time.Time)
	// permission.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	permission.UpdateDefaultUpdateTime = permissionDescUpdateTime.UpdateDefault.(func() time.Time)
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[0].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = func() func(string) error {
		validators := permissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescCode is the schema descriptor for code field.
	permissionDescCode := permissionFields[1].Descriptor()
	// permission.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	permission.CodeValidator = func() func(string) error {
		validators := permissionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescModule is the schema descriptor for module field.
	permissionDescModule := permissionFields[2].Descriptor()
	// permission.DefaultModule holds the default value on creation for the module field.
	permission.DefaultModule = permissionDescModule.Default.(string)
	// permission.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	permission.ModuleValidator = permissionDescModule.Validators[0].(func(string) error)
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[3].Descriptor()
	// permission.DefaultDescription holds the default value on creation for the description field.
	permission.DefaultDescription = permissionDescDescription.Default.(string)
	// permission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permission.DescriptionValidator = permissionDescDescription.Validators[0].(func(string) error)
	// permissionDescEnabled is the schema descriptor for enabled field.
	permissionDescEnabled := permissionFields[4].Descriptor()
	// permission.DefaultEnabled holds the default value on creation for the enabled field.
	permission.DefaultEnabled = permissionDescEnabled.Default.(bool)
	permissionauditlogMixin := schema.PermissionAuditLog{}.Mixin()
	permissionauditlogMixinFields0 := permissionauditlogMixin[0].Fields()
	_ = permissionauditlogMixinFields0
	permissionauditlogFields := schema.PermissionAuditLog{}.Fields()
	_ = permissionauditlogFields
	// permissionauditlogDescCreateTime is the schema descriptor for create_time field.
	permissionauditlogDescCreateTime := permissionauditlogMixinFields0[0].Descriptor()
	// permissionauditlog.DefaultCreateTime holds the default value on creation for the create_time field.
	permissionauditlog.DefaultCreateTime = permissionauditlogDescCreateTime.Default.(func() time.Time)
	// permissionauditlogDescAction is the schema descriptor for action field.
	permissionauditlogDescAction := permissionauditlogFields[1].Descriptor()
	// permissionauditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	permissionauditlog.ActionValidator = permissionauditlogDescAction.Validators[0].(func(string) error)
	// permissionauditlogDescTargetType is the schema descriptor for target_type field.
	permissionauditlogDescTargetType := permissionauditlogFields[2].Descriptor()
	// permissionauditlog.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	permissionauditlog.TargetTypeValidator = permissionauditlogDescTargetType.Validators[0].(func(string) error)
	// permissionauditlogDescRequestID is the schema descriptor for request_id field.
	permissionauditlogDescRequestID := permissionauditlogFields[4].Descriptor()
	// permissionauditlog.DefaultRequestID holds the default value on creation for the request_id field.
	permissionauditlog.DefaultRequestID = permissionauditlogDescRequestID.Default.(string)
	// permissionauditlog.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	permissionauditlog.RequestIDValidator = permissionauditlogDescRequestID.Validators[0].(func(string) error)
	// permissionauditlogDescIPAddress is the schema descriptor for ip_address field.
	permissionauditlogDescIPAddress := permissionauditlogFields[5].Descriptor()
	// permissionauditlog.DefaultIPAddress holds the default value on creation for the ip_address field.
	permissionauditlog.DefaultIPAddress = permissionauditlogDescIPAddress.Default.(string)
	// permissionauditlog.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	permissionauditlog.IPAddressValidator = permissionauditlogDescIPAddress.Validators[0].(func(string) error)
	permissiongroupMixin := schema.PermissionGroup{}.Mixin()
	permissiongroupMixinFields0 := permissiongroupMixin[0].Fields()
	_ = permissiongroupMixinFields0
	permissiongroupFields := schema.PermissionGroup{}.Fields()
	_ = permissiongroupFields
	// permissiongroupDescCreateTime is the schema descriptor for create_time field.
	permissiongroupDescCreateTime := permissiongroupMixinFields0[0].Descriptor()
	// permissiongroup.DefaultCreateTime holds the default value on creation for the create_time field.
	permissiongroup.DefaultCreateTime = permissiongroupDescCreateTime.Default.(func() time.Time)
	// permissiongroupDescUpdateTime is the schema descriptor for update_time field.
	permissiongroupDescUpdateTime := permissiongroupMixinFields0[1].Descriptor()
	// permissiongroup.DefaultUpdateTime holds the default value on creation for the update_time field.
	permissiongroup.DefaultUpdateTime = permissiongroupDescUpdateTime.Default.(func() time.Time)
	// permissiongroup.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	permissiongroup.UpdateDefaultUpdateTime = permissiongroupDescUpdateTime.UpdateDefault.(func() time.Time)
	// permissiongroupDescName is the schema descriptor for name field.
	permissiongroupDescName := permissiongroupFields[0].Descriptor()
	// permissiongroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permissiongroup.NameValidator = func() func(string) error {
		validators := permissiongroupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissiongroupDescModule is the schema descriptor for module field.
	permissiongroupDescModule := permissiongroupFields[1].Descriptor()
	// permissiongroup.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	permissiongroup.ModuleValidator = func() func(string) error {
		validators := permissiongroupDescModule.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(module string) error {
			for _, fn := range fns {
				if err := fn(module); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissiongroupDescDescription is the schema descriptor for description field.
	permissiongroupDescDescription := permissiongroupFields[2].Descriptor()
	// permissiongroup.DefaultDescription holds the default value on creation for the description field.
	permissiongroup.DefaultDescription = permissiongroupDescDescription.Default.(string)
	// permissiongroup.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permissiongroup.DescriptionValidator = permissiongroupDescDescription.Validators[0].(func(string) error)
	// permissiongroupDescSortOrder is the schema descriptor for sort_order field.
	permissiongroupDescSortOrder := permissiongroupFields[4].Descriptor()
	// permissiongroup.DefaultSortOrder holds the default value on creation for the sort_order field.
	permissiongroup.DefaultSortOrder = permissiongroupDescSortOrder.Default.(int)
	// permissiongroupDescEnabled is the schema descriptor for enabled field.
	permissiongroupDescEnabled := permissiongroupFields[5].Descriptor()
	// permissiongroup.DefaultEnabled holds the default value on creation for the enabled field.
	permissiongroup.DefaultEnabled = permissiongroupDescEnabled.Default.(bool)
	referralMixin := schema.Referral{}.Mixin()
	referralMixinFields0 := referralMixin[0].Fields()
	_ = referralMixinFields0
	referralFields := schema.Referral{}.Fields()
	_ = referralFields
	// referralDescCreateTime is the schema descriptor for create_time field.
	referralDescCreateTime := referralMixinFields0[0].Descriptor()
	// referral.DefaultCreateTime holds the default value on creation for the create_time field.
	referral.DefaultCreateTime = referralDescCreateTime.Default.(func() time.Time)
	// referralDescUpdateTime is the schema descriptor for update_time field.
	referralDescUpdateTime := referralMixinFields0[1].Descriptor()
	// referral.DefaultUpdateTime holds the default value on creation for the update_time field.
	referral.DefaultUpdateTime = referralDescUpdateTime.Default.(func() time.Time)
	// referral.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	referral.UpdateDefaultUpdateTime = referralDescUpdateTime.UpdateDefault.(func() time.Time)
	// referralDescReward is the schema descriptor for reward field.
	referralDescReward := referralFields[2].Descriptor()
	// referral.RewardValidator is a validator for the "reward" field. It is called by the builders before save.
	referral.RewardValidator = referralDescReward.Validators[0].(func(int) error)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreateTime is the schema descriptor for create_time field.
	roleDescCreateTime := roleMixinFields0[0].Descriptor()
	// role.DefaultCreateTime holds the default value on creation for the create_time field.
	role.DefaultCreateTime = roleDescCreateTime.Default.(func() time.Time)
	// roleDescUpdateTime is the schema descriptor for update_time field.
	roleDescUpdateTime := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdateTime holds the default value on creation for the update_time field.
	role.DefaultUpdateTime = roleDescUpdateTime.Default.(func() time.Time)
	// role.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	role.UpdateDefaultUpdateTime = roleDescUpdateTime.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[1].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = func() func(string) error {
		validators := roleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescEnabled is the schema descriptor for enabled field.
	roleDescEnabled := roleFields[3].Descriptor()
	// role.DefaultEnabled holds the default value on creation for the enabled field.
	role.DefaultEnabled = roleDescEnabled.Default.(bool)
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[4].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescCreditBalance is the schema descriptor for credit_balance field.
	userDescCreditBalance := userFields[3].Descriptor()
	// user.DefaultCreditBalance holds the default value on creation for the credit_balance field.
	user.DefaultCreditBalance = userDescCreditBalance.Default.(int)
	// user.CreditBalanceValidator is a validator for the "credit_balance" field. It is called by the builders before save.
	user.CreditBalanceValidator = userDescCreditBalance.Validators[0].(func(int) error)
	// userDescEnabled is the schema descriptor for enabled field.
	userDescEnabled := userFields[4].Descriptor()
	// user.DefaultEnabled holds the default value on creation for the enabled field.
	user.DefaultEnabled = userDescEnabled.Default.(bool)
}
