// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keep/sunny/ent/credittransaction"
	"github.com/keep/sunny/ent/predicate"
	"github.com/keep/sunny/ent/referral"
	"github.com/keep/sunny/ent/role"
	"github.com/keep/sunny/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdate) SetUpdateTime(v time.Time) *UserUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetReferralCode sets the "referral_code" field.
func (_u *UserUpdate) SetReferralCode(v string) *UserUpdate {
	_u.mutation.SetReferralCode(v)
	return _u
}

// SetNillableReferralCode sets the "referral_code" field if the given value is not nil.
func (_u *UserUpdate) SetNillableReferralCode(v *string) *UserUpdate {
	if v != nil {
		_u.SetReferralCode(*v)
	}
	return _u
}

// ClearReferralCode clears the value of the "referral_code" field.
func (_u *UserUpdate) ClearReferralCode() *UserUpdate {
	_u.mutation.ClearReferralCode()
	return _u
}

// SetCreditBalance sets the "credit_balance" field.
func (_u *UserUpdate) SetCreditBalance(v int) *UserUpdate {
	_u.mutation.ResetCreditBalance()
	_u.mutation.SetCreditBalance(v)
	return _u
}

// SetNillableCreditBalance sets the "credit_balance" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreditBalance(v *int) *UserUpdate {
	if v != nil {
		_u.SetCreditBalance(*v)
	}
	return _u
}

// AddCreditBalance adds value to the "credit_balance" field.
func (_u *UserUpdate) AddCreditBalance(v int) *UserUpdate {
	_u.mutation.AddCreditBalance(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserUpdate) SetEnabled(v bool) *UserUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEnabled(v *bool) *UserUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdate) ClearPasswordHash() *UserUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// AddSentReferralIDs adds the "sent_referrals" edge to the Referral entity by IDs.
func (_u *UserUpdate) AddSentReferralIDs(ids ...int) *UserUpdate {
	_u.mutation.AddSentReferralIDs(ids...)
	return _u
}

// AddSentReferrals adds the "sent_referrals" edges to the Referral entity.
func (_u *UserUpdate) AddSentReferrals(v ...*Referral) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentReferralIDs(ids...)
}

// SetReceivedReferralID sets the "received_referral" edge to the Referral entity by ID.
func (_u *UserUpdate) SetReceivedReferralID(id int) *UserUpdate {
	_u.mutation.SetReceivedReferralID(id)
	return _u
}

// SetNillableReceivedReferralID sets the "received_referral" edge to the Referral entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableReceivedReferralID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetReceivedReferralID(*id)
	}
	return _u
}

// SetReceivedReferral sets the "received_referral" edge to the Referral entity.
func (_u *UserUpdate) SetReceivedReferral(v *Referral) *UserUpdate {
	return _u.SetReceivedReferralID(v.ID)
}

// AddCreditTransactionIDs adds the "credit_transactions" edge to the CreditTransaction entity by IDs.
func (_u *UserUpdate) AddCreditTransactionIDs(ids ...int) *UserUpdate {
	_u.mutation.AddCreditTransactionIDs(ids...)
	return _u
}

// AddCreditTransactions adds the "credit_transactions" edges to the CreditTransaction entity.
func (_u *UserUpdate) AddCreditTransactions(v ...*CreditTransaction) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreditTransactionIDs(ids...)
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *UserUpdate) AddRoleIDs(ids ...int) *UserUpdate {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *UserUpdate) AddRoles(v ...*Role) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSentReferrals clears all "sent_referrals" edges to the Referral entity.
func (_u *UserUpdate) ClearSentReferrals() *UserUpdate {
	_u.mutation.ClearSentReferrals()
	return _u
}

// RemoveSentReferralIDs removes the "sent_referrals" edge to Referral entities by IDs.
func (_u *UserUpdate) RemoveSentReferralIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveSentReferralIDs(ids...)
	return _u
}

// RemoveSentReferrals removes "sent_referrals" edges to Referral entities.
func (_u *UserUpdate) RemoveSentReferrals(v ...*Referral) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentReferralIDs(ids...)
}

// ClearReceivedReferral clears the "received_referral" edge to the Referral entity.
func (_u *UserUpdate) ClearReceivedReferral() *UserUpdate {
	_u.mutation.ClearReceivedReferral()
	return _u
}

// ClearCreditTransactions clears all "credit_transactions" edges to the CreditTransaction entity.
func (_u *UserUpdate) ClearCreditTransactions() *UserUpdate {
	_u.mutation.ClearCreditTransactions()
	return _u
}

// RemoveCreditTransactionIDs removes the "credit_transactions" edge to CreditTransaction entities by IDs.
func (_u *UserUpdate) RemoveCreditTransactionIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveCreditTransactionIDs(ids...)
	return _u
}

// RemoveCreditTransactions removes "credit_transactions" edges to CreditTransaction entities.
func (_u *UserUpdate) RemoveCreditTransactions(v ...*CreditTransaction) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreditTransactionIDs(ids...)
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *UserUpdate) ClearRoles() *UserUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *UserUpdate) RemoveRoleIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *UserUpdate) RemoveRoles(v ...*Role) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.CreditBalance(); ok {
		if err := user.CreditBalanceValidator(v); err != nil {
			return &ValidationError{Name: "credit_balance", err: fmt.Errorf(`ent: validator failed for field "User.credit_balance": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferralCode(); ok {
		_spec.SetField(user.FieldReferralCode, field.TypeString, value)
	}
	if _u.mutation.ReferralCodeCleared() {
		_spec.ClearField(user.FieldReferralCode, field.TypeString)
	}
	if value, ok := _u.mutation.CreditBalance(); ok {
		_spec.SetField(user.FieldCreditBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreditBalance(); ok {
		_spec.AddField(user.FieldCreditBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(user.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if _u.mutation.SentReferralsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentReferralsTable,
			Columns: []string{user.SentReferralsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentReferralsIDs(); len(nodes) > 0 && !_u.mutation.SentReferralsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentReferralsTable,
			Columns: []string{user.SentReferralsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentReferralsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentReferralsTable,
			Columns: []string{user.SentReferralsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReceivedReferralCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ReceivedReferralTable,
			Columns: []string{user.ReceivedReferralColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceivedReferralIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ReceivedReferralTable,
			Columns: []string{user.ReceivedReferralColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreditTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreditTransactionsTable,
			Columns: []string{user.CreditTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreditTransactionsIDs(); len(nodes) > 0 && !_u.mutation.CreditTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreditTransactionsTable,
			Columns: []string{user.CreditTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreditTransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreditTransactionsTable,
			Columns: []string{user.CreditTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: user.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: user.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: user.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdateOne) SetUpdateTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetReferralCode sets the "referral_code" field.
func (_u *UserUpdateOne) SetReferralCode(v string) *UserUpdateOne {
	_u.mutation.SetReferralCode(v)
	return _u
}

// SetNillableReferralCode sets the "referral_code" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableReferralCode(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetReferralCode(*v)
	}
	return _u
}

// ClearReferralCode clears the value of the "referral_code" field.
func (_u *UserUpdateOne) ClearReferralCode() *UserUpdateOne {
	_u.mutation.ClearReferralCode()
	return _u
}

// SetCreditBalance sets the "credit_balance" field.
func (_u *UserUpdateOne) SetCreditBalance(v int) *UserUpdateOne {
	_u.mutation.ResetCreditBalance()
	_u.mutation.SetCreditBalance(v)
	return _u
}

// SetNillableCreditBalance sets the "credit_balance" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreditBalance(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetCreditBalance(*v)
	}
	return _u
}

// AddCreditBalance adds value to the "credit_balance" field.
func (_u *UserUpdateOne) AddCreditBalance(v int) *UserUpdateOne {
	_u.mutation.AddCreditBalance(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserUpdateOne) SetEnabled(v bool) *UserUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEnabled(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdateOne) ClearPasswordHash() *UserUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// AddSentReferralIDs adds the "sent_referrals" edge to the Referral entity by IDs.
func (_u *UserUpdateOne) AddSentReferralIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddSentReferralIDs(ids...)
	return _u
}

// AddSentReferrals adds the "sent_referrals" edges to the Referral entity.
func (_u *UserUpdateOne) AddSentReferrals(v ...*Referral) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentReferralIDs(ids...)
}

// SetReceivedReferralID sets the "received_referral" edge to the Referral entity by ID.
func (_u *UserUpdateOne) SetReceivedReferralID(id int) *UserUpdateOne {
	_u.mutation.SetReceivedReferralID(id)
	return _u
}

// SetNillableReceivedReferralID sets the "received_referral" edge to the Referral entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableReceivedReferralID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetReceivedReferralID(*id)
	}
	return _u
}

// SetReceivedReferral sets the "received_referral" edge to the Referral entity.
func (_u *UserUpdateOne) SetReceivedReferral(v *Referral) *UserUpdateOne {
	return _u.SetReceivedReferralID(v.ID)
}

// AddCreditTransactionIDs adds the "credit_transactions" edge to the CreditTransaction entity by IDs.
func (_u *UserUpdateOne) AddCreditTransactionIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddCreditTransactionIDs(ids...)
	return _u
}

// AddCreditTransactions adds the "credit_transactions" edges to the CreditTransaction entity.
func (_u *UserUpdateOne) AddCreditTransactions(v ...*CreditTransaction) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreditTransactionIDs(ids...)
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *UserUpdateOne) AddRoleIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *UserUpdateOne) AddRoles(v ...*Role) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSentReferrals clears all "sent_referrals" edges to the Referral entity.
func (_u *UserUpdateOne) ClearSentReferrals() *UserUpdateOne {
	_u.mutation.ClearSentReferrals()
	return _u
}

// RemoveSentReferralIDs removes the "sent_referrals" edge to Referral entities by IDs.
func (_u *UserUpdateOne) RemoveSentReferralIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveSentReferralIDs(ids...)
	return _u
}

// RemoveSentReferrals removes "sent_referrals" edges to Referral entities.
func (_u *UserUpdateOne) RemoveSentReferrals(v ...*Referral) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentReferralIDs(ids...)
}

// ClearReceivedReferral clears the "received_referral" edge to the Referral entity.
func (_u *UserUpdateOne) ClearReceivedReferral() *UserUpdateOne {
	_u.mutation.ClearReceivedReferral()
	return _u
}

// ClearCreditTransactions clears all "credit_transactions" edges to the CreditTransaction entity.
func (_u *UserUpdateOne) ClearCreditTransactions() *UserUpdateOne {
	_u.mutation.ClearCreditTransactions()
	return _u
}

// RemoveCreditTransactionIDs removes the "credit_transactions" edge to CreditTransaction entities by IDs.
func (_u *UserUpdateOne) RemoveCreditTransactionIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveCreditTransactionIDs(ids...)
	return _u
}

// RemoveCreditTransactions removes "credit_transactions" edges to CreditTransaction entities.
func (_u *UserUpdateOne) RemoveCreditTransactions(v ...*CreditTransaction) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreditTransactionIDs(ids...)
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *UserUpdateOne) ClearRoles() *UserUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *UserUpdateOne) RemoveRoleIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *UserUpdateOne) RemoveRoles(v ...*Role) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.CreditBalance(); ok {
		if err := user.CreditBalanceValidator(v); err != nil {
			return &ValidationError{Name: "credit_balance", err: fmt.Errorf(`ent: validator failed for field "User.credit_balance": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferralCode(); ok {
		_spec.SetField(user.FieldReferralCode, field.TypeString, value)
	}
	if _u.mutation.ReferralCodeCleared() {
		_spec.ClearField(user.FieldReferralCode, field.TypeString)
	}
	if value, ok := _u.mutation.CreditBalance(); ok {
		_spec.SetField(user.FieldCreditBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreditBalance(); ok {
		_spec.AddField(user.FieldCreditBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(user.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if _u.mutation.SentReferralsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentReferralsTable,
			Columns: []string{user.SentReferralsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentReferralsIDs(); len(nodes) > 0 && !_u.mutation.SentReferralsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentReferralsTable,
			Columns: []string{user.SentReferralsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentReferralsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentReferralsTable,
			Columns: []string{user.SentReferralsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReceivedReferralCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ReceivedReferralTable,
			Columns: []string{user.ReceivedReferralColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceivedReferralIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ReceivedReferralTable,
			Columns: []string{user.ReceivedReferralColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreditTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreditTransactionsTable,
			Columns: []string{user.CreditTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreditTransactionsIDs(); len(nodes) > 0 && !_u.mutation.CreditTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreditTransactionsTable,
			Columns: []string{user.CreditTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreditTransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreditTransactionsTable,
			Columns: []string{user.CreditTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: user.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: user.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: user.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
