// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/keep/sunny/ent/referral"
	"github.com/keep/sunny/ent/user"
)

// User table stores all user information.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// ReferralCode holds the value of the "referral_code" field.
	ReferralCode *string `json:"referral_code,omitempty"`
	// CreditBalance holds the value of the "credit_balance" field.
	CreditBalance int `json:"credit_balance,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// SentReferrals holds the value of the sent_referrals edge.
	SentReferrals []*Referral `json:"sent_referrals,omitempty"`
	// ReceivedReferral holds the value of the received_referral edge.
	ReceivedReferral *Referral `json:"received_referral,omitempty"`
	// CreditTransactions holds the value of the credit_transactions edge.
	CreditTransactions []*CreditTransaction `json:"credit_transactions,omitempty"`
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// SentReferralsOrErr returns the SentReferrals value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentReferralsOrErr() ([]*Referral, error) {
	if e.loadedTypes[0] {
		return e.SentReferrals, nil
	}
	return nil, &NotLoadedError{edge: "sent_referrals"}
}

// ReceivedReferralOrErr returns the ReceivedReferral value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ReceivedReferralOrErr() (*Referral, error) {
	if e.ReceivedReferral != nil {
		return e.ReceivedReferral, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: referral.Label}
	}
	return nil, &NotLoadedError{edge: "received_referral"}
}

// CreditTransactionsOrErr returns the CreditTransactions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CreditTransactionsOrErr() ([]*CreditTransaction, error) {
	if e.loadedTypes[2] {
		return e.CreditTransactions, nil
	}
	return nil, &NotLoadedError{edge: "credit_transactions"}
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[3] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldEnabled:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldCreditBalance:
			values[i] = new(sql.NullInt64)
		case user.FieldName, user.FieldEmail, user.FieldReferralCode, user.FieldPasswordHash:
			values[i] = new(sql.NullString)
		case user.FieldCreateTime, user.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case user.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldReferralCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referral_code", values[i])
			} else if value.Valid {
				_m.ReferralCode = new(string)
				*_m.ReferralCode = value.String
			}
		case user.FieldCreditBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_balance", values[i])
			} else if value.Valid {
				_m.CreditBalance = int(value.Int64)
			}
		case user.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySentReferrals queries the "sent_referrals" edge of the User entity.
func (_m *User) QuerySentReferrals() *ReferralQuery {
	return NewUserClient(_m.config).QuerySentReferrals(_m)
}

// QueryReceivedReferral queries the "received_referral" edge of the User entity.
func (_m *User) QueryReceivedReferral() *ReferralQuery {
	return NewUserClient(_m.config).QueryReceivedReferral(_m)
}

// QueryCreditTransactions queries the "credit_transactions" edge of the User entity.
func (_m *User) QueryCreditTransactions() *CreditTransactionQuery {
	return NewUserClient(_m.config).QueryCreditTransactions(_m)
}

// QueryRoles queries the "roles" edge of the User entity.
func (_m *User) QueryRoles() *RoleQuery {
	return NewUserClient(_m.config).QueryRoles(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	if v := _m.ReferralCode; v != nil {
		builder.WriteString("referral_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("credit_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditBalance))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
