// Code generated by ent, DO NOT EDIT.

package referral

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/keep/sunny/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldUpdateTime, v))
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldInviterID, v))
}

// InviteeID applies equality check predicate on the "invitee_id" field. It's identical to InviteeIDEQ.
func InviteeID(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldInviteeID, v))
}

// Reward applies equality check predicate on the "reward" field. It's identical to RewardEQ.
func Reward(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReward, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldUpdateTime, v))
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldInviterID, v))
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldInviterID, v))
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldInviterID, vs...))
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldInviterID, vs...))
}

// InviteeIDEQ applies the EQ predicate on the "invitee_id" field.
func InviteeIDEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldInviteeID, v))
}

// InviteeIDNEQ applies the NEQ predicate on the "invitee_id" field.
func InviteeIDNEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldInviteeID, v))
}

// InviteeIDIn applies the In predicate on the "invitee_id" field.
func InviteeIDIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldInviteeID, vs...))
}

// InviteeIDNotIn applies the NotIn predicate on the "invitee_id" field.
func InviteeIDNotIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldInviteeID, vs...))
}

// RewardEQ applies the EQ predicate on the "reward" field.
func RewardEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReward, v))
}

// RewardNEQ applies the NEQ predicate on the "reward" field.
func RewardNEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldReward, v))
}

// RewardIn applies the In predicate on the "reward" field.
func RewardIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldReward, vs...))
}

// RewardNotIn applies the NotIn predicate on the "reward" field.
func RewardNotIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldReward, vs...))
}

// RewardGT applies the GT predicate on the "reward" field.
func RewardGT(v int) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldReward, v))
}

// RewardGTE applies the GTE predicate on the "reward" field.
func RewardGTE(v int) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldReward, v))
}

// RewardLT applies the LT predicate on the "reward" field.
func RewardLT(v int) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldReward, v))
}

// RewardLTE applies the LTE predicate on the "reward" field.
func RewardLTE(v int) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldReward, v))
}

// HasInviter applies the HasEdge predicate on the "inviter" edge.
func HasInviter() predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviterWith applies the HasEdge predicate on the "inviter" edge with a given conditions (other predicates).
func HasInviterWith(preds ...predicate.User) predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := newInviterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvitee applies the HasEdge predicate on the "invitee" edge.
func HasInvitee() predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, InviteeTable, InviteeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviteeWith applies the HasEdge predicate on the "invitee" edge with a given conditions (other predicates).
func HasInviteeWith(preds ...predicate.User) predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := newInviteeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreditTransaction applies the HasEdge predicate on the "credit_transaction" edge.
func HasCreditTransaction() predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CreditTransactionTable, CreditTransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreditTransactionWith applies the HasEdge predicate on the "credit_transaction" edge with a given conditions (other predicates).
func HasCreditTransactionWith(preds ...predicate.CreditTransaction) predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := newCreditTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Referral) predicate.Referral {
	return predicate.Referral(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Referral) predicate.Referral {
	return predicate.Referral(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Referral) predicate.Referral {
	return predicate.Referral(sql.NotPredicates(p))
}
