// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/credit-transactions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Referrals"
                ],
                "summary": "List all referral credit transactions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.CreditTransactionListAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/referral-stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Referrals"
                ],
                "summary": "Get global referral reward statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.StatsAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/referrals": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Referrals"
                ],
                "summary": "List all referral rewards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.ReferralListAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/google/callback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Complete Google OAuth login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Google authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.APIError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/errors.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/google/login": {
            "get": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Start Google OAuth login",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/errors.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/referrals/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referrals"
                ],
                "summary": "Register a new user through an invitation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.RegistrationAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "description": "Retrieve the authenticated user's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get current user",
                "operationId": "getCurrentUser",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user",
                        "schema": {
                            "$ref": "#/definitions/response.UserAPIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.APIError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errors.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/referral-code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referrals"
                ],
                "summary": "Generate or return a user's invitation link",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.InvitationAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/referral-dashboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referrals"
                ],
                "summary": "Get referral statistics, history and credit ledger",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.DashboardAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.CreditTransactionListAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/admin.CreditTransactionListView"
                }
            }
        },
        "admin.CreditTransactionListView": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.CreditTransactionView"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/internal_modules_referral_admin.PaginationView"
                }
            }
        },
        "admin.CreditTransactionView": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "referralId": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/internal_modules_referral_admin.UserView"
                }
            }
        },
        "admin.ReferralListAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/admin.ReferralListView"
                }
            }
        },
        "admin.ReferralListView": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_referral_admin.ReferralView"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/internal_modules_referral_admin.PaginationView"
                }
            }
        },
        "admin.StatsAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/admin.StatsView"
                }
            }
        },
        "admin.StatsView": {
            "type": "object",
            "properties": {
                "totalCreditsAwarded": {
                    "type": "integer"
                },
                "totalInviters": {
                    "type": "integer"
                },
                "totalReferrals": {
                    "type": "integer"
                },
                "totalUsers": {
                    "type": "integer"
                }
            }
        },
        "auth.LoginAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/auth.LoginView"
                }
            }
        },
        "auth.LoginView": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "isNewUser": {
                    "type": "boolean"
                },
                "tokenType": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.UserView"
                }
            }
        },
        "auth.UserView": {
            "type": "object",
            "properties": {
                "creditBalance": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "referralCode": {
                    "type": "string"
                }
            }
        },
        "client.CreditTransactionView": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "referralId": {
                    "type": "integer"
                }
            }
        },
        "client.DashboardAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/client.DashboardView"
                }
            }
        },
        "client.DashboardView": {
            "type": "object",
            "properties": {
                "creditTransactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.CreditTransactionView"
                    }
                },
                "referrals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.ReferralView"
                    }
                },
                "successfulReferrals": {
                    "type": "integer"
                },
                "totalCreditsEarned": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/client.UserView"
                }
            }
        },
        "client.InvitationAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/client.InvitationView"
                }
            }
        },
        "client.InvitationView": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "client.ReferralView": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invitee": {
                    "$ref": "#/definitions/client.UserView"
                },
                "reward": {
                    "type": "integer"
                }
            }
        },
        "client.RegistrationAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/client.RegistrationView"
                }
            }
        },
        "client.RegistrationView": {
            "type": "object",
            "properties": {
                "invitee": {
                    "$ref": "#/definitions/client.UserView"
                },
                "inviterCreditBalance": {
                    "type": "integer"
                },
                "reward": {
                    "type": "integer"
                }
            }
        },
        "client.UserView": {
            "type": "object",
            "properties": {
                "creditBalance": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "referralCode": {
                    "type": "string"
                }
            }
        },
        "ent.UserEntity": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "creditBalance": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "referralCode": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        },
        "errors.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_modules_referral_admin.PaginationView": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_referral_admin.ReferralView": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invitee": {
                    "$ref": "#/definitions/internal_modules_referral_admin.UserView"
                },
                "inviter": {
                    "$ref": "#/definitions/internal_modules_referral_admin.UserView"
                },
                "reward": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_referral_admin.UserView": {
            "type": "object",
            "properties": {
                "creditBalance": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "referralCode": {
                    "type": "string"
                }
            }
        },
        "response.UserAPIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "payload": {
                    "$ref": "#/definitions/ent.UserEntity"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIAuth": {
            "type": "apiKey",
            "name": "app_cookie_name",
            "in": "cookie"
        },
        "OpenAPIAuth": {
            "type": "apiKey",
            "name": "PRIVATE-TOKEN",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin APP API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
