// Code generated by ent, DO NOT EDIT.

package credittransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/keep/sunny/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldUpdateTime, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldUserID, v))
}

// ReferralID applies equality check predicate on the "referral_id" field. It's identical to ReferralIDEQ.
func ReferralID(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldReferralID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldAmount, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldReason, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLTE(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldUserID, vs...))
}

// ReferralIDEQ applies the EQ predicate on the "referral_id" field.
func ReferralIDEQ(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldReferralID, v))
}

// ReferralIDNEQ applies the NEQ predicate on the "referral_id" field.
func ReferralIDNEQ(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldReferralID, v))
}

// ReferralIDIn applies the In predicate on the "referral_id" field.
func ReferralIDIn(vs ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldReferralID, vs...))
}

// ReferralIDNotIn applies the NotIn predicate on the "referral_id" field.
func ReferralIDNotIn(vs ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldReferralID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLTE(FieldAmount, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.FieldContainsFold(FieldReason, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CreditTransaction {
	return predicate.CreditTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CreditTransaction {
	return predicate.CreditTransaction(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferral applies the HasEdge predicate on the "referral" edge.
func HasReferral() predicate.CreditTransaction {
	return predicate.CreditTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ReferralTable, ReferralColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferralWith applies the HasEdge predicate on the "referral" edge with a given conditions (other predicates).
func HasReferralWith(preds ...predicate.Referral) predicate.CreditTransaction {
	return predicate.CreditTransaction(func(s *sql.Selector) {
		step := newReferralStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreditTransaction) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreditTransaction) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreditTransaction) predicate.CreditTransaction {
	return predicate.CreditTransaction(sql.NotPredicates(p))
}
